Fix test with Python 3.9.2+
aio-libs/yarl pull request #575
Opened 2021-04-16 19:17 UTC by shadchin

## What do these changes do?

Fixes #563 

## Are there changes in behavior for the user?

Yes

## Related issue number

https://bugs.python.org/issue42967

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

2021-04-17 23:08 UTC, webknjaz commented on yarl/_url.py
> +                )
This should address the LGTM alert
```suggestion
                )  # lgtm [py/call/wrong-named-argument]
```

2021-04-17 23:24 UTC, webknjaz requested changes
Do we really need to change the API of `yarl.URL()`? This PR needs more work introducing better compatibility shims. Otherwise, it may be easier to just always pass an ampersand w/o changing the API.

2021-04-17 23:24 UTC, webknjaz commented on yarl/_url.py
> +            or sys.version_info >= (3, 9, 2)
This module is not the right place for such conditionals. We should put `parse_qsl()` compat code into a `_compat` module and then import it here + use w/o conditionals.

2021-04-17 23:24 UTC, webknjaz commented on yarl/_url.py
> +    def __new__(cls, val="", *, encoded=False, strict=None, separator="&"):
If we start providing this public API to the end-users, we must ensure that users calling it with `separator=";"` on old and new Pythons will get the same results regardless of whether the underlying function in stdlib supports this argument or not.

This means, that we need a compatibility shim in the `_compat` module normalizing the behavior across the board.

2021-04-17 23:24 UTC, webknjaz commented on tests/test_url_query.py
> +    u = URL("http://127.0.0.1/?a=1;b=2", separator=";")
This will fail under some environments unless the behavior isn't made predictable. Also, we probably need tests with combinations of `;` and `&`.

2021-04-17 23:24 UTC, webknjaz commented on CHANGES/563.bugfix
> +Fix issue with semicolon as a separator in query parameters.
As it stands now, this PR also adds a feature of passing a separator arg to the constructor. So this probably shouldn't be a `.bugfix` file.

2021-04-17 23:24 UTC, webknjaz commented on CHANGES/563.bugfix
> +Fix issue with semicolon as a separator in query parameters.
Also, this note is supposed to be user-oriented. When somebody reads the changelog, it should give them some idea of what this is about. It currently does not name the issue, nor does it mention the way it's addressed and what the impact is for the users.

2021-05-28 11:25 UTC, asvetlov commented
Thanks for the PR.
I rather prefer to drop the test and give up the semicolon separator support.
It is a very rarely used mode, I never saw it in the real-life since about 1999.

2021-05-28 11:25 UTC, closed without merging